//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATALAYER
{
    using System;

    public partial class DATDICHVU_TBL
    {
        public string MADATDICHVU { get; set; }
        public string MADICHVU { get; set; }
        public string MAPHONGDAT { get; set; }
        public int SOLUONG { get; set; }
        public System.DateTime NGAYDAT { get; set; }
        public int GIADICHVU { get; set; }
        public string MATRANGTHAI { get; set; }
        public string MAHOADONDV { get; set; }

        public virtual DICHVU_TBL DICHVU_TBL { get; set; }
        public virtual HOADONDATDV_TBL HOADONDATDV_TBL { get; set; }
        public virtual PHONGDAT_TBL PHONGDAT_TBL { get; set; }
        public virtual TRANGTHAIDATDV_TBL TRANGTHAIDATDV_TBL { get; set; }
    }
}
