//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATALAYER
{
    using System;

    public partial class HOADONPHONG_TBL
    {
        public string MAHOADON { get; set; }
        public string MAPHONGDAT { get; set; }
        public string MATRANGTHAI { get; set; }
        public System.DateTime NGAYTHANHTOAN { get; set; }
        public string MATHOIDIEM { get; set; }
        public int GIATRIBANDAU { get; set; }
        public int GIAMGIA { get; set; }
        public int GIATHANHTOAN { get; set; }

        public virtual PHONGDAT_TBL PHONGDAT_TBL { get; set; }
        public virtual TRANGTHAIHD_TBL TRANGTHAIHD_TBL { get; set; }
        public virtual PAYMENTTIME_TBL PAYMENTTIME_TBL { get; set; }
    }
}
