//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATALAYER
{
    using System;
    using System.Collections.Generic;

    public partial class KHACHHANG_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG_TBL()
        {
            this.PHONGDAT_TBL = new HashSet<PHONGDAT_TBL>();
        }

        public string IDKHACH { get; set; }
        public string HOVATEN { get; set; }
        public string MAGT { get; set; }
        public string SOLIENHE { get; set; }
        public string EMAIL { get; set; }
        public string QUEQUAN { get; set; }
        public string MAQT { get; set; }

        public virtual GIOITINH_TBL GIOITINH_TBL { get; set; }
        public virtual QUOCTICH_TBL QUOCTICH_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONGDAT_TBL> PHONGDAT_TBL { get; set; }
    }
}
