//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATALAYER
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class QLKSEntities : DbContext
    {
        public QLKSEntities()
            : base("name=QLKSEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<DATDICHVU_TBL> DATDICHVU_TBL { get; set; }
        public virtual DbSet<DICHVU_TBL> DICHVU_TBL { get; set; }
        public virtual DbSet<GIOITINH_TBL> GIOITINH_TBL { get; set; }
        public virtual DbSet<HOADONDATDV_TBL> HOADONDATDV_TBL { get; set; }
        public virtual DbSet<HOADONPHONG_TBL> HOADONPHONG_TBL { get; set; }
        public virtual DbSet<KHACHHANG_TBL> KHACHHANG_TBL { get; set; }
        public virtual DbSet<LOAIDV_TBL> LOAIDV_TBL { get; set; }
        public virtual DbSet<LOAIHINHDP_TBL> LOAIHINHDP_TBL { get; set; }
        public virtual DbSet<LOAIHINHDV_TBL> LOAIHINHDV_TBL { get; set; }
        public virtual DbSet<LOAIPHONG_TBL> LOAIPHONG_TBL { get; set; }
        public virtual DbSet<NHANVIEN_TBL> NHANVIEN_TBL { get; set; }
        public virtual DbSet<PAYMENTTIME_TBL> PAYMENTTIME_TBL { get; set; }
        public virtual DbSet<PHONGDAT_TBL> PHONGDAT_TBL { get; set; }
        public virtual DbSet<PHONGNGHI_TBL> PHONGNGHI_TBL { get; set; }
        public virtual DbSet<QUOCTICH_TBL> QUOCTICH_TBL { get; set; }
        public virtual DbSet<TANGHOTEL_TBL> TANGHOTEL_TBL { get; set; }
        public virtual DbSet<TINHTRANGPHONG_TBL> TINHTRANGPHONG_TBL { get; set; }
        public virtual DbSet<TRANGTHAIDATDV_TBL> TRANGTHAIDATDV_TBL { get; set; }
        public virtual DbSet<TRANGTHAIDP_TBL> TRANGTHAIDP_TBL { get; set; }
        public virtual DbSet<TRANGTHAIDV_TBL> TRANGTHAIDV_TBL { get; set; }
        public virtual DbSet<TRANGTHAIHD_TBL> TRANGTHAIHD_TBL { get; set; }
        public virtual DbSet<TRANGTHAINV_TBL> TRANGTHAINV_TBL { get; set; }
        public virtual DbSet<TRANGTHAIPHONG_TBL> TRANGTHAIPHONG_TBL { get; set; }
        public virtual DbSet<QUYENHAN_TBL> QUYENHAN_TBL { get; set; }
        public virtual DbSet<TAIKHOAN_TBL> TAIKHOAN_TBL { get; set; }
    }
}
