//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATALAYER
{
    using System;

    public partial class NHANVIEN_TBL
    {
        public string IDNV { get; set; }
        public string HOVATEN { get; set; }
        public byte[] HINHNEN { get; set; }
        public string MAGT { get; set; }
        public string SOLIENHE { get; set; }
        public string EMAIL { get; set; }
        public string QUEQUAN { get; set; }
        public string MAQT { get; set; }
        public System.DateTime NGAYHIEULUC { get; set; }
        public string MATRANGTHAI { get; set; }

        public virtual GIOITINH_TBL GIOITINH_TBL { get; set; }
        public virtual QUOCTICH_TBL QUOCTICH_TBL { get; set; }
        public virtual TRANGTHAINV_TBL TRANGTHAINV_TBL { get; set; }
        public virtual TAIKHOAN_TBL TAIKHOAN_TBL { get; set; }
    }
}
