//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATALAYER
{
    using System;
    using System.Collections.Generic;

    public partial class PHONGDAT_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONGDAT_TBL()
        {
            this.DATDICHVU_TBL = new HashSet<DATDICHVU_TBL>();
            this.HOADONPHONG_TBL = new HashSet<HOADONPHONG_TBL>();
        }

        public string MAPHONGDAT { get; set; }
        public string IDKHACH { get; set; }
        public string MAPHONG { get; set; }
        public System.DateTime NGAYDAT { get; set; }
        public System.DateTime NGAYLAY { get; set; }
        public System.DateTime NGAYTRA { get; set; }
        public decimal THOIHAN { get; set; }
        public string MALOAIHINH { get; set; }
        public int GIAPHONG { get; set; }
        public string MATRANGTHAI { get; set; }
        public string GHICHU { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATDICHVU_TBL> DATDICHVU_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONPHONG_TBL> HOADONPHONG_TBL { get; set; }
        public virtual KHACHHANG_TBL KHACHHANG_TBL { get; set; }
        public virtual LOAIHINHDP_TBL LOAIHINHDP_TBL { get; set; }
        public virtual PHONGNGHI_TBL PHONGNGHI_TBL { get; set; }
        public virtual TRANGTHAIDP_TBL TRANGTHAIDP_TBL { get; set; }
    }
}
