//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATALAYER
{
    using System;
    using System.Collections.Generic;

    public partial class PHONGNGHI_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONGNGHI_TBL()
        {
            this.PHONGDAT_TBL = new HashSet<PHONGDAT_TBL>();
        }

        public string MAPHONG { get; set; }
        public string TENPHONG { get; set; }
        public int TANGTHU { get; set; }
        public string MALOAIPHONG { get; set; }
        public string MATINHTRANG { get; set; }
        public string MATRANGTHAI { get; set; }

        public virtual LOAIPHONG_TBL LOAIPHONG_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONGDAT_TBL> PHONGDAT_TBL { get; set; }
        public virtual TANGHOTEL_TBL TANGHOTEL_TBL { get; set; }
        public virtual TINHTRANGPHONG_TBL TINHTRANGPHONG_TBL { get; set; }
        public virtual TRANGTHAIPHONG_TBL TRANGTHAIPHONG_TBL { get; set; }
    }
}
